---
stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.surfedu.nl/edu/analyzer:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: registry.surfedu.nl/edu/analyzer:latest

build docker image:
  stage: build
  image: docker:latest
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASS registry.surfedu.nl
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - docker
  only:
    - master

release image prod:
  stage: release
  image: docker:stable
  tags:
    - docker
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASS registry.surfedu.nl
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy to stack:
  stage: deploy
  script:
    - ssh deploy@dev01.swarm.surfedu.nl  "sudo docker service update --with-registry-auth --image $CONTAINER_RELEASE_IMAGE surfpol-stack_analyzer"
  tags:
    - shell
  only:
    - master
