---
stages:
  - build
  - deploy

variables:
  CONTAINER_LATEST_IMAGE: registry.metadata.surfcatalog.nl/oom/analyzer:latest

build docker image:
  stage: build
  image: docker:latest
  script:
    - docker build --pull -t $CONTAINER_LATEST_IMAGE .
    - docker push $CONTAINER_LATEST_IMAGE
  tags:
    - docker-ci-metadata-runner

deploy docker container:
  stage: deploy
  script:
    - docker stack deploy --prune --compose-file docker-compose.yml analyzer
  tags:
    - shell-ci-metadata-runner
